<?php

/**
 * @file
 * Contains eleague_blocks.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eleague_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the eleague_blocks module.
    case 'help.page.eleague_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module for holding ELEAGUE blocks') . '</p>';
      return $output;

    default:
  }
}
